# Generated by Django 3.2.13 on 2022-06-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('price', models.IntegerField(default=8, verbose_name='价格')),
                ('pub_date', models.DateField(verbose_name='出版日期')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
