# Generated by Django 3.2.13 on 2022-06-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_author_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20, verbose_name='名称')),
                ('hgender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='性别')),
                ('hbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '英雄',
                'db_table': 'heros',
            },
        ),
    ]
